server:
  port: 8085
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:6543/car_post_storage
    password: '2515'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
